tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.2/types.yaml
  - plugin:cloudify-openstack-plugin

inputs:

  keystone_username:
    default: { get_secret: keystone_username }

  keystone_password:
    default: { get_secret: keystone_password }

  keystone_tenant_name:
    default: { get_secret: keystone_tenant_name }

  keystone_url:
    default: { get_secret: keystone_url }

  region:
    default: { get_secret: region }


dsl_definitions:
  openstack_config: &OPENSTACK_CONFIG
    username: { get_input: keystone_username }
    password: { get_input: keystone_password }
    tenant_name: { get_input: keystone_tenant_name }
    auth_url: { get_input: keystone_url }
    region: { get_input: region }

node_templates:

  router:
    type: cloudify.openstack.nodes.Router
    properties:
      use_external_resource: true
      resource_id:  { get_secret: router_name }
      openstack_config: *OPENSTACK_CONFIG

  routes_1:
    type: cloudify.openstack.nodes.Routes
    properties:
      routes:
        - destination: 192.168.121.0/24
          nexthop: 192.168.120.123
      openstack_config: *OPENSTACK_CONFIG
    relationships:
      - target: router
        type: cloudify.openstack.route_connected_to_router

  routes_2:
    type: cloudify.openstack.nodes.Routes
    properties:
      routes:
        - destination: 10.10.0.0/16
          nexthop: 192.168.120.123
      openstack_config: *OPENSTACK_CONFIG
    relationships:
      - target: router
        type: cloudify.openstack.route_connected_to_router
